### ISSUE TITLE
Test SpriteBatch 

### ISSUE THREAD

**Issue by Arcane561** [TomGrill/gdx-testing#5]
Hi, I tried to test the game and the test fails. It fails when creating a SpriteBatch, namely in the compileShaders method. 
StackTrace Error:
```java 
java.lang.NullPointerException
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.loadShader(ShaderProgram.java:209)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.compileShaders(ShaderProgram.java:188)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:171)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:162)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
	at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:100)
	at com.mygdx.game.screens.MenuScreen.<init>(MenuScreen.java:24)
	at com.mygdx.game.SimpleAndroidGame.create(SimpleAndroidGame.java:28)
	at com.mygdx.game.screens.MenuScreenTest.setUp(MenuScreenTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.mygdx.game.ecs.components.GdxTestRunner.render(GdxTestRunner.java:43)
	at com.badlogic.gdx.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:129)
	at com.badlogic.gdx.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:96)

**Comment by TomGrill** [comment]
The lib is not really meant to test libGDX specific stuff like SpriteBatch etc. Often times mocking everything up consumes much more time than it is worth. Keep tests to data classes or game logic stuff. Anything that is represented visually on the screen anyway you can test during development since you will see it like 100 times a day :)

**Comment by Arcane561** [comment]
Thank you very much
